# Generated by Django 2.1.4 on 2018-12-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdb_app', '0004_auto_20181221_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
